#Copyright [2025] [Chris Sherwood]
 # 
 # Licensed under the Apache License, Version 2.0...
 # 
 # --- MODIFICAÇÕES ---
 # Modificado por [Miguel Forggia Ferreira] em [2026].
 # Alterações feitas para adicionar suporte a [Tradução PTBR].

blank_issues_enabled: false
contact_links:
  - name: 💬 Comunidade do Discord  
    url: https://discord.com/invite/crosstalksolutions
    about: Entre em nossa comunidade no Discord para questões gerais, suporte e discurssões     
  - name: 📖 Documentação 
    url: https://projectnomad.us
    about: Consulte a documentos oficiais e guias    
  - name: 🏆 Ranking da Comunidade
    url: https://benchmark.projectnomad.us
    about: Veja o ranking de desempenho do NOMAD
  - name: 🤝 Guia de Contribuição
    url: https://github.com/Crosstalk-Solutions/project-nomad/blob/main/CONTRIBUTING.md
    about: Aprenda como contribuir com o Project NOMAD  
  - name: 📅 Roadmap
    url: https://roadmap.projectnomad.us
    about: Veja nosso roadmap, vote em funcionalidades e sugira novas funcionalidades
